### ISSUE TITLE
Edit dates with a calendar (<input type="date">)

### ISSUE THREAD

**Issue by stla** [rstudio/DT#1064]
@yihui 

As we said two days ago, it would be nice to be able to edit dates with an `<input type="date">` in a **DT** table.

I could do it but I'm not very familiar with dates in R. I think `is(x, "Date")` is ok to detect a date (this is the way used in **lubridate**). Once we get a date in this way, it remains to format it as `yyyy-mm-dd` in order to pass it to JavaScript. How to do that? I quickly searched on StackOverflow but all the answers I found suggest to use a package such as **lubridate** or **anytime**. Are you ok for importing a new package in **DT**?

**Comment by stla** [comment]
`parse_date_time` in **lubridate** is not nice because one has to know the format of the input dates. `anytime::anydate` is better.

**Comment by yihui** [comment]
For detecting dates, you can use `inherits(x, 'Date')`. Dates are automatically converted to the `YYYY-mm-dd` format via **jsonlite**. We don't need to do this by ourselves.

To support `date` inputs, I think we can let users specify the column indices in R:

https://github.com/rstudio/DT/blob/8e983673aed8d32aa5d6b651c2a3ea45239e47aa/R/datatables.R#L318-L322

Then in JS we use `<input type="date">`:

https://github.com/rstudio/DT/blob/6073c02f66cf4925d078bf32f37851b1172ef943/inst/htmlwidgets/datatables.js#L831-L837

Of course, it will be nice to automatically detect dates and use `date` inputs, instead of manually specifying the column indices.

Currently we know which columns are dates only when column filters are present:

https://github.com/rstudio/DT/blob/8e983673aed8d32aa5d6b651c2a3ea45239e47aa/R/datatables.R#L673-L675

https://github.com/rstudio/DT/blob/8e983673aed8d32aa5d6b651c2a3ea45239e47aa/inst/htmlwidgets/datatables.js#L82
