### ISSUE TITLE
custom container with colspan 1 moves sort icon up

### ISSUE THREAD

**Issue by vnijs** [rstudio/DT#156]
Minor issue but with the code below the sort icon moves up a row when colspan = 1. I could use rowspan = 2 to address this but ...

![screen shot 2015-07-31 at 7 02 57 pm](https://cloud.githubusercontent.com/assets/2998956/9020281/bdacf02e-37b7-11e5-8a5f-d04d558e4633.png)

Example in Data > Explore: http://vnijs.rady.ucsd.edu:3838/base/?SSUID=f9bf1e2596 

```r
  ## cn_... are the categorical, numeric, and all variables in the tab
  sketch = shiny::withTags(table(
    thead(
      tr(
        th(" ", colspan = length(cn_cat)),
        lapply(top, th, colspan = length(cn_num), class = "text-center")
      ),
      tr(lapply(cn_all, th))
    )
  ))
```

**Comment by yihui** [comment]
When `filter = 'top'`, I move the sort buttons to the top row because by default the buttons will be displayed beside the search boxes (they are the bottom row in the table header), which is undesirable: https://github.com/rstudio/DT/blob/9d0940782e7986513ab7daa9385d7816b7c828ae/R/datatables.R#L150-L152

I don't have a good solution for this case. Sorry.

**Comment by vnijs** [comment]
Too bad. Thanks @yihui
