### ISSUE TITLE
ionRangeSlider used in Shiny, but noUISlider in DT filters - ?

### ISSUE THREAD

**Issue by GitChub** [rstudio/DT#232]
I'm not sure if this is an issue or a "feature".  : )

Regardless, I'm looking for input on how best to harmonize the appearance and styling of Shiny sliders and DT filter sliders.  Any suggestions are appreciated.

It's fairly straightforward to have a uniform color scheme using a little custom CSS.  I'm more interested in  how one might make the slider knobs consistent and make the other aspects of the appearance of sliders be uniform.

**Comment by yihui** [comment]
Originally Shiny was not using ionRangeSlider but another slider library (I don't remember exactly what it was). I did some research on existing slider libraries, and I found noUISlider to be the most lightweight. I didn't need many fancy features, so I just integrated it into DT. Since the sliders in the table are hidden behind the search boxes by default, I guess it does not really bother users too much.

It is probably not very easy to make it look very similar to ionRangeSlider, but if you really want to customize its appearance, you can just go the usual route -- right click the slider in Google Chrome, and poke around its CSS rules in the developer tools.

**Comment by jkraut** [comment]
Is there anyting preventing the override of the noUISlider styles in DT?  I have a datatable embedded in a shiny app with custom .css, but supplying overrides for the relevant noUISlider styles doesn't seem to have an effect.

`.noUi-connect {
    background: #2F57BB;
}`

**Comment by GitChub** [comment]
@jkraut Just CSS precedence rules.  You can first confirm that the following works and then, if you so desire, look for a less "brute force", yet still higher precedence, selector:

`.noUi-connect { background: #2F57BB  !important;}`

**Comment by jkraut** [comment]
Ah, right!  Still a bit of a novice when it comes to CSS and wasn't thinking about precedence.  Thanks for the prompt reply!

**Comment by GitChub** [comment]
No problem.  Was just looking at this a bit more closely to confirm that the precedence rule that was almost certainly thwarting your background color change is the fact that the jquery.nouislider.min.css file comes after your custom CSS file in the <head> of the generated HTML.  That jquery.nouislider.min.css file also uses the ".noUi-connect" class selector; so it's at the same level of specificity as your selector and, in that case, the CSS rule is that whichever one comes later wins.

A simple way to have a slightly more specific selector and avoid the brute force "!important" would be to do this:

`div.noUi-connect { background: #2F57BB; }`

That should also work.

**Comment by jkraut** [comment]
Interestingly enough, neither of these work.  Seems like they should, but for some reason the appearance keeps defaulting to the standard noUI color.

**Comment by GitChub** [comment]
@jkraut Hmmmm... Only thing I can think of is that your browser is using the cached, previous version of your custom CSS file, perhaps?  To force a cache reload in a web browser on Windows, I think it's Ctrl + F5 (or Ctrl + Shift + R). On a Mac, Cmd + Shift + R.

**Comment by jkraut** [comment]
Thanks for all the help!  I realized the problem was related to how flexdashboard applies css.  I added the changes to the .css file I was supplying in the .yaml for the flexdashboard content, but failed to realize this wouldn't automatically apply those styles to embedded Shiny Modules.  A simple `includeCSS("./custom.css"),` embedded within the UI component of my Shiny Module did the trick.
