### ISSUE TITLE
Doesn't play well with knitr caching

### ISSUE THREAD

**Issue by longouyang** [rstudio/DT#30]
If I want to use `datatable` inside an R Markdown chunk, caching fails.

Here's an example document:

    ---
    title: "foo"
    output: html_document
    ---
    
    ```{r, cache=TRUE}
    DT::datatable(data.frame(x=runif(50),y=runif(50)))
    ```
The error I get on trying to knit this is:

````
Quitting from lines 7-8 (foo.Rmd) 
Error in wrap.knit_asis(X[[2L]], ...) : 
  The code chunk 'unnamed-chunk-1' is not cacheable; please use the chunk option cache=FALSE on this chunk
Calls: <Anonymous> ... wrap -> wrap.list -> lapply -> FUN -> wrap.knit_asis
Execution halted
````

**Comment by yihui** [comment]
The error message said exactly what you should do. HTML widgets are not supposed to be cached. If your code chunk involves heavy computation, please move the computation to another chunk and cache that one. The code chunk that renders the widget must not be cached, otherwise knitr/rmarkdown will not know what dependencies are required to render the widget later in HTML.

**Comment by longouyang** [comment]
I guess I assumed that the datatable command emitted raw HTML+JS as output, which would be suitable for caching, but it sounds like that's not the case.

**Comment by yihui** [comment]
The raw HTML+JS can certainly be cached. It is the dependencies of HTML+JS that cannot.

**Comment by longouyang** [comment]
Forgive my ignorance; in the example I provided, the chunk containing the datatable call doesn't depend on anything. Do DT internals create some dependencies that I can't control?

**Comment by yihui** [comment]
This is a general htmlwidgets issue, not specific to DT. All HTML widgets almost surely have additional dependencies, such as jQuery and other JS libraries. 

Since you seem to be interested, here is the R code to attach dependencies to the table widget: https://github.com/rstudio/DT/blob/9ecc51b5fcba94fa7a714fc1781d9f8f171e86e4/R/datatables.R#L182-L187 And here are the JS/CSS dependencies: https://github.com/rstudio/DT/tree/master/inst/htmlwidgets/lib

May I ask you why you need to cache the widget? And what is the problem with the approach that I described in my very first reply? Thanks!

**Comment by longouyang** [comment]
I'm trying to set up a workflow that lets me rapidly explore the space of possible reports (i.e., generated HTML files) very quickly.

To this end, I'm taking a cache-everything approach, which means I can very quickly switch between the updated knitted output to see if it's to my liking and the RStudio for chunk editing and session exploration (which I keep in sync with knitr by `lazyLoad`ing all the rdx files in knitr cache folder).

I guess this workflow won't play well with widgets because, as you point out, there is stateful dependency loading to get them to load both in RStudio and the browser environment. Maybe RStudio in general isn't a good tool for this (or maybe this workflow is just a bad idea)

**Comment by yihui** [comment]
Have you measured the time to render your widgets? In other words, is it a real bottleneck? We can definitely consider improving the speed when it is a real blocking issue.

BTW, fundamentally this is irrelevant to the RStudio IDE. The IDE just happens to be the viewer of the output. Under the hood, it is knitr and rmarkdown that compile and render the document.

**Comment by andreifoldes** [comment]
I'm experiencing a similar problem whereby I find it convenient to use "cache all" in the knitr.options but would like the htmlwidgets - like DT - to ignore that. 

Is there any way to implement this? Just create separate html widget chunks with "cache=FALSE" ?
