### ISSUE TITLE
datatable seed bug with .Rmd

### ISSUE THREAD

**Issue by carloscinelli** [rstudio/DT#307]
If you set the same seed twice during the code it does not evaluate the table correctly. See example 
below:

-----------

<div>
<p>
---
</p>
<p>
title: "datatable bug"
</p>
<p>
output:  ioslides_presentation
</p>
<p>
---
</p>

<p>```{r setup, include=FALSE} </p>
<p> knitr::opts_chunk$set(echo = T) </p>
<p>``` </p>

<p>## mtcars</p>

<p>```{r}</p>
<p>set.seed(10)</p>
<p>library(DT)</p>
<p>datatable(mtcars)</p>
<p>```</p>

<p>## repeat seed for bug</p>

<p>```{r}</p>
<p>set.seed(10)</p>
<p>```</p>

<p>## should be iris but mtcars again</p>

<p>```{r}</p>
<p>datatable(iris)</p>
<p>```</p>
</div>

**Comment by yihui** [comment]
This is an htmlwidgets issue, and you can post to https://github.com/ramnathv/htmlwidgets/issues htmlwidgets may need something like `shiny:::withPrivateSeed` to avoid issues like this.

**Comment by carloscinelli** [comment]
Thanks, Yihui, just posted it there too.

**Comment by timelyportfolio** [comment]
This is in my mind a design problem, but I have not thought of any clean ways to deal with it except require `htmlwidget` authors to provide an id.  `htmlwidget::createWidget` does provide an argument `elementId`, but `DT` does not expose this argument.  Would it be possible for `DT` to add `elementId` as an optional argument that would get passed through to these [lines](https://github.com/rstudio/DT/blob/master/R/datatables.R#L247-L271)?  Otherwise a hack to manually specify an `elementId` is 

```
library(DT)
d <- datatable(mtcars)
d$elementId <- 'my_unique_table_id_1'
d

d2 <- datatable(cars)
d$elementId <- 'a_manual_id'
d2
```

**Comment by timelyportfolio** [comment]
For an example in a `htmlwidget, see `sunburst` lines [49](https://github.com/timelyportfolio/sunburstR/blob/master/R/sunburst.R#L49) and [lines](https://github.com/timelyportfolio/sunburstR/blob/master/R/sunburst.R#L81-L89).

**Comment by yihui** [comment]
`elementId` has been added to `datatable()`, but this issue has already been solved in the development version of htmlwidgets anyway: https://github.com/ramnathv/htmlwidgets
