### ISSUE TITLE
Cannot select rows with shinydashboard

### ISSUE THREAD

**Issue by jcdepth** [rstudio/DT#321]
Hi,

I have a Shiny app that has two datatables. Please note that the app works perfectly on my local machine, which runs OS X El Capitan. I am using `shinydashboard` for the layout.

The first datatable is a datatable of terms, with the relevant column being of the class `chr`. The user clicks on the run, and I pass along `s = input$DT1_rows_selected`, to extract the relevant term from the datatable: `DT1$x$data$term[s]`. My app then searches strings, and outputs a second datatable, `DT2`, which displays normally on my local machine.

The issue is that in an AWS Ubuntu environment, I am not even able to highlight/select a row. On my local machine, whenever I click on a row, the row will turn blue as expected. On the server version, even though I can't select rows, sorting columns and search seem to work fine.

I am running DT `0.1.57`, installed directly from Github with `devtools`.

Interesting enough, right now I have the two datatables displayed on two different tabs. In this scenario, `DT2` just never outputs data, and remains empty. If I have both datatables on the same tab, I unable to sort or interact with `DT1` at all, and get a permanent `Processing...` message overlayed on `DT1`.

I realize this is a fairly obscure issue, but I would appreciate any help. The ability to select rows is critical to my app being completed. Thanks!

**Comment by jcdepth** [comment]
I should add that I did not specify the `style = "bootstrap"` parameter in the options for the datatable, and that seems to work fine on my local machine, even when the app is launched in a browser.

**Comment by jcdepth** [comment]
I did some further experimentation. On the server environment, if I make some kind of trivial change to the `ui.R` file, selection briefly works. However, as soon as the files that are read into `DT1` and `DT2` are changed, selection no longer works. I then need to go ahead and make some other change to the `ui.R` file again to make selection function again.

Is this some kind of cache issue with `DT`? Is there a way to implement cache busting?

**Comment by yihui** [comment]
There isn't any caching in DT. To start debugging the issue, I need either a minimal reproducible example, or a URL of your app that I can visit. You can send it to me in private email if you prefer.

**Comment by jcdepth** [comment]
Hi yihui, just sent you the app via email. Thanks!

**Comment by yihui** [comment]
Okay, I looked at your app, and it seems it was still using DT 0.1, so you may

```r
devtools::install_github('rstudio/DT')
```

on your server to update DT there.

**Comment by jcdepth** [comment]
So I was confused because at the bottom of my page, I had a `textOutput` that was using `packageVersion()` to get package loaded. I suspect however, that the version of `DT` used was different from what was being indicated in the `textOutput`. After I went ahead and reinstalled my R environment on a new Ubuntu 14 instance on AWS, I set my `Renviron` file explicitly, I had no issues.

I found this guide to be very useful: https://www.datascienceriot.com/install-shiny-server-for-r-on-ubuntu-the-right-way/kris/, particularly step 5. Thanks for all the help.

**Comment by yihui** [comment]
Yes, it is possible that you installed different versions of the same package to different R libraries. You can inspect the output of

```r
sapply(.libPaths(), list.files)
```

to see if DT was installed in multiple places. For Shiny Server, you almost always have to install R packages with `sudo` to avoid installing to a personal library under the home directory (`~/R/xxx-library/...`), because these packages will be ignored by Shiny Server unless you have set `Renviron` correctly. It is a bad idea to edit Renviron, though, because after you upgrade R, all changes in `Renviron` will be lost, and you are likely to be confused again...

**Comment by jcdepth** [comment]
Thanks, will use `Renviron` with caution. The thing that still puzzles me is that in some instances, my desired datatable rendered correctly, in others it did not. Is there not a consistent logic or priority in loading R libraries?

**Comment by yihui** [comment]
The logic is consistent -- looking for packages in every library available in `.libPaths()`. It is the personal library `~/R/` that can screw up things. Well, preciously speaking, it is because the home directory `~` can be different for different users. Shiny Server may run your apps using a different user with the one you used to log in. In other words, if you install a package in your personal library, the other user will not see it. All system library paths are visible to all users, such as those ones under `/usr/...`.
