### ISSUE TITLE
Filter character columns like factor columns

### ISSUE THREAD

**Issue by nuno-agostinho** [rstudio/DT#331]
Since I'm working with really big data frames, it's much preferable to load data with characters instead of factors. Unfortunately, the filter of DataTables doesn't present the useful dropdown in columns of the character class with the unique values of that column.

Could this be implemented (or at least be an option)?

**Comment by dmenne** [comment]
I support this issue. Below is an example. It is very confusing, that smart filtering works with data.frame (assuming default string as factors), but fails with tibble where usually a string is stored.

```
library(shiny)
library(DT)

ui <- fluidPage(DT::dataTableOutput("car_table"))

server <- function(input, output) {
   output$car_table = DT::renderDataTable({
     mt = data.frame(car = rownames(mtcars), mpg = mtcars[,1])
     #mt$car = as.character(mt$car) # Uncomment, and no more smart search
     DT::datatable(mt, rownames = FALSE,
                   filter = "top",
                   options = list(paging = FALSE))
   })
}

# Run the application
shinyApp(ui = ui, server = server)


```

**Comment by yihui** [comment]
@dmenne I guess I should not be responsible for the confusion caused by the default `stringsAsFactors = TRUE` in base R.

@nuno-agostinho I don't see why it is preferable. Aren't factors (essentially integers with a few character labels) typically more efficient than characters when the data frames are big?

```r
> x = sample(letters, 1000000, TRUE)
> object.size(x)
8001288 bytes
> object.size(factor(x))
4001856 bytes
```

It can be very, very inefficient to support character columns as factors in **DT** in the column filters, when a column contains a huge number of "categories". It may even crash your web browser is the number is big enough.

**Comment by lizthompson07** [comment]
In case it is helpful to anyone because in upgrading to R 4.0+ I ran into this when importing a .csv file and creating a datatable with filtering. In previous versions it worked fine (must have converted columns to factors instead of characters automatically?). I spent a couple hours trying to figure out why my datatable column filters were no longer showing the text options. Finally thought to check class(mydf$column) to discover they were characters and not factors.  Hope this helps someone else with the same problem!
