### ISSUE TITLE
horizontal scroll bar with shinydashboard

### ISSUE THREAD

**Issue by matt6890122** [rstudio/DT#34]
Hi Yihui,

It seems there is a problem when a shiny app displays a dataframe with many columns with shiny dashboard : 
```
library(shiny)
library(shinydashboard)
library(DT)

ui = dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody(DT::dataTableOutput('tbl'))
)
server = function(input, output, session) {
  output$tbl = DT::renderDataTable({
    DT::datatable(volcano, filter = 'top', options = list(autoWidth = T))
  })
}
runApp(list(ui=ui,server=server))
```
I don't have any horizontal scroll bar at the bottom.

Matthieu

**Comment by matt6890122** [comment]
Actually, if we add the option : scrollX = T, it works perfectly. Sorry about that. 
And thanks again for this wonderful package.

**Comment by wch** [comment]
This is the same issue as rstudio/shinydashboard#22.

**Comment by yihui** [comment]
It turns out it is very difficult to position the filters when scrolling is enabled in DataTables. I only managed to fix the bug of initializing the filters, but the scrolling issue is really tricky. What you may do alternatively is to wrap the table in a div with `overflow-x: scroll`, e.g.

```r
  dashboardBody(
    div(style = 'overflow-x: scroll', DT::dataTableOutput('tbl'))
  )
```

This is not a perfect solution, but is the best thing I can offer at the moment.

Note you need to install the latest version of DT here.

**Comment by matt6890122** [comment]
It does the trick. Thanks again for your responsiveness :)

**Comment by CaptainKatsuura** [comment]
Hi, I can see how this would have a scrollbar specifically for the datatable, but is a similar approach applicable to overall pages like vertical scrollbars are? 

Thanks
