### ISSUE TITLE
Can't apply options to selectizeInput in datatable

### ISSUE THREAD

**Issue by carlganz** [rstudio/DT#390]
When I try to apply options to a `selectizeInput` inside a datatable it fails to use any of the options.

```{R}
library(shiny)
library(DT)

# stolen from Yihui somewhere
shinyInput = function(FUN, len, id, ...) {
  inputs = character(len)
  for (i in seq_len(len)) {
    inputs[i] = as.character(FUN(paste0(id, i), label = NULL, ...))
  }
  inputs
}

ui <- fluidPage(
  mainPanel(
    selectizeInput("one",NULL, 1:3, options = list(
      placeholder = "test",
      onInitialize=I(
        "function() {this.setValue('')}"
      )
    )),
    DT::dataTableOutput("two")
  )
)

server <- shinyServer(function(input, output, session) {
  
  output$two <- DT::renderDataTable({
    data.frame(x1=1:2,
               x2 = shinyInput(selectizeInput, 2, "test",
                               choices = 1:3,
                               options = list(
                                 placeholder ="test",
# onInitialize is not respected here
                                 onInitialize=I(
                                   "function() {this.setValue('')}"
                                 ))))
  }, escape = FALSE, selection = list(mode=FALSE), options = list(
    preDrawCallback = DT::JS(
      'function() {
        Shiny.unbindAll(this.api().table().node())
      }'
    ),
    drawCallback = DT::JS(
      'function(settings) {
        Shiny.bindAll(this.api().table().node())
      }'
    )))
  
  observe({
    print(input$test1)
  })
  
})

shinyApp(ui=ui, server=server)
```

In general I've never found adding shiny inputs to datatables to be very straightforward especially if the inputs in the datatable have to be re-rendered at any point. Unfortunately I don't have any suggestions at the moment for improvements.

Thanks

**Comment by carlganz** [comment]
In the meantime I added this to `drawCallback`, which manually removes values from the inputs:

```{javascript}
        l = this.api().table().data().length;
        for (i = 1;i<l+1; i++) {
          document.getElementById("upcodeVal"+i).value = "";
        }
```

**Comment by yihui** [comment]
`selectizeInput()` won't work inside a table. You copied my code from https://github.com/rstudio/DT/issues/93#issuecomment-111001538. Actually I was wrong -- you cannot use arbitrary Shiny inputs in the table. Only those inputs that are pure HTML and do not involve JavaScript will work. `selectizeInput()` is JS-based. What you saw was a normal `<select>` input and not selectize.

**Comment by stla** [comment]
You have to apply `selectize()` to the element. See <https://stackoverflow.com/a/55041373/1100107>.

**Comment by mmuurr** [comment]
FWIW, I think this _is_ doable, though there are probably some good reasons not to do this. For starters, if your table changes frequently, this has the downside of constantly unbinding-then-initializing-and-then-rebinding inputs within the DT. I haven't tested this with `dataTableProxy`, though I think this would work, as fundamentally we're attaching callback hooks to DT's rendering events.

```R
    output[["the_datatable"]] <- DT::renderDataTable({
      tbl <- tibble::tibble(
        row_name = "row 1",
        input_element = as.character(selectizeInput("inner_selectize_input", label = "inner_selectize_input", choices = c("foo","bar","baz"), options = list(create = TRUE)))
      )
      DT::datatable(
        tbl,
        escape = 0,
        selection = "none",
        options = list(
          preDrawCallback = DT::JS("function(settings) {
            Shiny.unbindAll(this.api().table().node());
          }"),
          drawCallback = DT::JS("function(settings) {
            Shiny.initializeInputs(this.api().table().node());
            Shiny.bindAll(this.api().table().node());
          }")
        )
      )
    })
```
You can add as many `input_element`s as you like and just dynamically construct their input IDs (as shown in the example above).

The key here is the `Shiny.initializeInputs()` call in the `drawCallback`.

That technically _can_ be replaced by a direct attempt to initialize the Selectize library on the element (as mentioned by @stla), **but** Shiny's SelectInputBinding [does a few other things](https://github.com/rstudio/shiny/blob/main/srcts/src/bindings/input/selectInput.ts#L207) that are nice to fully replicate. Since the binding's `initialize()` method is called prior to the actual data binding, the `Shiny.bindAll()` call bypasses it, and thus keeps the element as plain HTML `<select>` -- which I think is the core of the problem described in this thread. Keeping the `Shiny.initializeInputs`, `Shiny.unbindAll`, and `Shiny.bindAll` calls all scoped to the table itself prevents re-initializing and breaking other Shiny input/output elements on the page.

This might actually be a good reason to eventually include a `initialize = true` default optional value to the `Shiny.bindAll()` function (which would then include the binding's `initialize()` method during the bind procedure). I'll think about that some more and perhaps start a thread/PR over on [rstudio/shiny] with this as the use case.

**Comment by rafaelcardosoargus** [comment]
> 

now that's what I call a nice solution!
