### ISSUE TITLE
CRAN Warnings for Solaris and realease OSX

### ISSUE THREAD

**Issue by eribul** [rstudio/DT#395]
Some warnings causing problems also for packages dependent on DT:
https://cran.r-project.org/web/checks/check_results_DT.html

**Comment by eribul** [comment]
> Version: 0.2 
> Check: re-building of vignette outputs 
> Result: WARN 
>     Error in re-building vignettes:
>      ...
>     Warning in engine$weave(file, quiet = quiet, encoding = enc) :
>      Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
>     Quitting from lines 23-25 (DT.Rmd) 
>     Error: processing vignette 'DT.Rmd' failed with diagnostics:
>     cannot open the connection
>     Execution halted 
> Flavors: r-patched-solaris-sparc, r-patched-solaris-x86
> 
> Version: 0.2 
> Check: re-building of vignette outputs 
> Result: WARN 
>     Error in re-building vignettes:
>      ...
>     Warning in (if (grepl("\\.[Rr]md$", file)) knit2html else if (grepl("\\.[Rr]rst$", :
>      It seems you should call rmarkdown::render() instead of knitr::knit2html() because DT.Rmd appears to be an R Markdown v2 document.
>     Quitting from lines 23-25 (DT.Rmd) 
>     Error: processing vignette 'DT.Rmd' failed with diagnostics:
>     cannot open the connection
>     Execution halted 
> Flavor: r-release-osx-x86_64-maveric

**Comment by yihui** [comment]
> causing problems also for packages dependent on DT

Could you tell me which packages are affected?

If you use **DT** in your vignettes, I recommend that you add the chunk option `screenshot.force = FALSE` like I did in 5154bc1e8f4079e828c59bd2879f3b673798d8d6. This is because on some CRAN machines, it seems Pandoc is not available, in which case webshot and PhantomJS are needed by default to screenshot the DT widget, and unfortunately PhantomJS may not be available on these machines, either, which leads to the error you currently see on CRAN.

Thanks!
