### ISSUE TITLE
Filter range sliders disappearing

### ISSUE THREAD

**Issue by JoshMB8** [rstudio/DT#402]
Hi, 

I'm fairly new to using DT in R and I'm coming up with a problem using the filter function.

When I create a table with purely numerical values the filters work as expected, however if I have a single column with non-numerical values they disappear. 

I am not sure what I am doing wrong. I have been looking through the documentation, and googling, for a couple of weeks now and haven't managed to find a solution. 

I am unable to include an example using my data as the data itself is confidential, as it is part of a University project, however I have included a very basic example I tested and came up with the same problem.

```
tmp <- c(1:10)
tmp2 <- c(11:20)
tmp3 <- c("A","B","A","A","B","B","A","B","A","A")

test <- cbind(tmp, tmp2, tmp3)
datatable(test, filter = 'top')

```

Any help with this problem would be greatly appreciated. 

Thank you.

**Comment by yihui** [comment]
That is because `cbind()` converted your numeric columns to characters:

```r
> str(test)
 chr [1:10, 1:3] "1" "2" "3" "4" "5" "6" "7" "8" "9" "10" "11" "12" "13" "14" "15" ...
 - attr(*, "dimnames")=List of 2
  ..$ : NULL
  ..$ : chr [1:3] "tmp" "tmp2" "tmp3"
```

In the future, please try to [ask questions on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead (with minimal, self-contained, and reproducible examples) and tag your question with `r` and `dt`. If you are not sure if it is a bug report or a question, consider using StackOverflow first (I closely watch StackOverflow questions every day). Thanks!
