### ISSUE TITLE
cell selection column index start from 0

### ISSUE THREAD

**Issue by dracodoc** [rstudio/DT#427]
@yihui When using cell selection mode, the `input$tableId_cells_selected` matrix have the cell column index start from 0.

If I'm understanding correctly, javascript have index start from 0, but other places of DT have did the conversion to make sure R code still use 1 index. For consistency maybe this also should be converted.

**Comment by shrektan** [comment]
Sorry for the late reply but the index starts from zero only when `rownames` is set to `FALSE`. I'm not sure the initial design reasons but I doubt we are going to change this because it will break lots of existing codes. 

So I'm going to close this and thanks for the report.

```r
library(shiny)
ui = basicPage(
  verbatimTextOutput('print'),
  checkboxInput('show_rowname', 'show rowname or not', value = TRUE),
  DT::DTOutput('tbl')
)
server = function(input, output, session) {
  output$tbl = DT::renderDT(
    DT::datatable(iris, selection = list(target = 'cell'), rownames = input$show_rowname)
  )
  output$print = renderPrint(input$tbl_cells_selected)
}
runApp(mget(c('ui', 'server')))
```

<img width="725" alt="image" src="https://user-images.githubusercontent.com/8368933/73596341-3fec9b00-455c-11ea-8829-3066190f54fd.png">
