### ISSUE TITLE
Decimals over range slider

### ISSUE THREAD

**Issue by Rabecerra** [rstudio/DT#433]
Hi all, I was working with a range slider and in the column only exists whole numbers, when you use the slider will appear 2 decimals on it, although there are no Decimals in the column, you can see here an example about this https://yihui.shinyapps.io/DT-filter/ on hp column is happening this. Any ideas of why is this happening? Thank you.

**Comment by XD-DENG** [comment]
Hi @Rabecerra , my understanding is you want integers (without decimal) in the range slider?

If yes, let's use the example in https://yihui.shinyapps.io/DT-filter/. If you apply function `str` on the data `mtcars2` or invoke`class(mtcars$hp)`, you will notice column `hp` is of class `numeric`, even if all values in this column are integers. 

This can be easily figured out by explicitly convert your column into class `integer`.  For the example in https://yihui.shinyapps.io/DT-filter/, if you add one line 

``` r
mtcars2$hp <- as.integer(mtcars2$hp)
```

the range slider will show integers rather than appearing any decimal, which is what you want.

**Comment by yihui** [comment]
That is exactly correct.
