### ISSUE TITLE
Internationalisation plug-ins

### ISSUE THREAD

**Issue by ycphs** [rstudio/DT#436]
Is there a way to call the Internationalisation plug-ins from https://datatables.net/plug-ins/i18n/?

Thank you.

**Comment by asayat** [comment]
Isn't it calling language in DT options?

https://rstudio.github.io/DT/004-i18n.html

From tutorial:
datatable(iris2, options = list(
  language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json'),
  pageLength = 5
))

**Comment by tfulge** [comment]
For me, calling the internationalisation plugin works, the way described above. However, when I try to render markdown documents in html, the specified language only shows up in RStudios viewer pane, but not when the .html-file is opened in an browser.

I am clueless as to why this is the case - any ideas?

**Comment by yihui** [comment]
It is caused by the [protocol-relative URL](https://www.paulirish.com/2010/the-protocol-relative-url/). I recommend you to add `https:` before `//` in the URL.

BTW, I can only handle Github issues for bug reports and feature requests, and I don't have time to answer general questions. Please try to [ask future questions on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) with tags `r` and `dt` instead (with minimal, self-contained, and reproducible examples). If you are not sure if it is a bug report or a question, consider using StackOverflow first (I closely watch StackOverflow questions every day). Thanks!

**Comment by tfulge** [comment]
Sure, I am kind of new to Github and SO and didn't fully realize Github is for bug reports and feature requests only, so please let me apologize. (For what it is worth, I had tried using the `https:` prefix but that did not solve the issue.)

**Comment by yihui** [comment]
Usually you can ask questions on Github. For me, [this is not practical](https://yihui.name/en/2017/08/so-gh-email/) since I usually don't have time to deal with general questions, and I don't want you to wait for two years for me to answer questions when there is a better place (StackOverflow) to ask questions.
