### ISSUE TITLE
rowreorder functionality

### ISSUE THREAD

**Issue by mearsdj** [rstudio/DT#437]
Hi,
Rowreorder doesn't seem to work properly when moving a row more than one position. Instead of the dragged row being added in to the new space, it appears to move the row that you've dragged one below or above it's old position. Then the row that you're dragging your existing row on top of then takes the position of the originally moved row. 
For a more coherent explanation, here's an example from the page here:
https://rstudio.github.io/DT/extensions.html
The original order is 1-10 inclusive
I dragged row 3 over top of row 7, expecting the order to become 1/2/4/5/6/3/7/8/9/10, but the resultant order was: 1/2/7/3/4/5/6/8/9/10.

**Comment by nuno-agostinho** [comment]
As according to the [DT 0.5 change log](https://github.com/rstudio/DT/releases/tag/v0.5):

> The RowReorder extension now works (thanks, @shrektan, #595 #592)

However, the behaviour when reordering rows is still not the one expected, as previously stated by @mearsdj. Could you please fix this? Thank you.

**Comment by prncevince** [comment]
@mearsdj @nuno-agostinho 

Looks like the option in [datatables.R](https://github.com/rstudio/DT/blob/ac6802a4f5b84b60d7db918ec55eee051d4658b9/R/datatables.R#L143) to have no ordering applied during initialization (canceling the default `order` parameter) is causing this unexpected behavior. It seems that simply setting `order` back to [its default](https://datatables.net/reference/option/order#Examples) creates expected behavior (see example below). 

Useful links for understanding the RowReorder extension a little more deeply [Basic Initialization](https://datatables.net/extensions/rowreorder/examples/initialisation/simple.html) & [Full Row Selection](https://datatables.net/extensions/rowreorder/examples/initialisation/selector.html). 

```R
library(DT)
library(tibble)
guy <- as.tibble(cbind(ID = 1:150, iris),rownames = NULL)
datatable(data = guy, extensions = "RowReorder",
          options = list(rowReorder = 'true',
                         order = list(c(0,'asc')), 
          rownames = TRUE))
```

**Comment by shrektan** [comment]
Thanks. Yes,  or you can click the header ID in https://rstudio.github.io/DT/extensions.html and then drag the row... The JS datatables library requires this... I'll update the RowReorder example in https://rstudio.github.io/DT/extensions.html later...
