### ISSUE TITLE
Incorrect Column Index when rownames = FALSE

### ISSUE THREAD

**Issue by ckatsulis** [rstudio/DT#446]
When the argument  `rownames = FALSE`  is included and a list of `order` column numbers and direction is included in the options, the index that is used to sort is 1 too high.  The code works as anticipated if `rownames` is set to `TRUE`

```
output$df= DT::renderDataTable(data(), 
                                      options = list(
                                        order = list(which(names(data()) == "fillTime"), 'desc')
                                      ),
                                      rownames = FALSE
  )
```

**Comment by shrektan** [comment]
This is  a documented behavior, see https://rstudio.github.io/DT/

> Influence of Row Names on Column Indices in JavaScript
Row names are essentialy a new column added to the original data (via cbind(rownames(data), data)). This has an important consequence in terms of the column indices. JavaScript indexes from 0 instead of 1, so the index of the n-th element is actually n - 1.1 When thinking of the column indices (which you will often have to do if you customize options), use

> **n - 1 as the index of the n-th column in the original data if you do not display row names;**
**n as the index of the n-th column in the original data if you want to display row names**, because the original index is n - 1 in JavaScript but we added the row names as the first column, and (n - 1) + 1 = n;
It is very important to remember this when using DataTables options.
