### ISSUE TITLE
Embed HTML

### ISSUE THREAD

**Issue by mfost** [rstudio/DT#45]
I'm trying to embed Facebook posts into a data table within shinydashboard, but while the table appears, it appears to just have empty rows when escape=FALSE. I've checked and the HTML code that is shown in the table (when escape=TRUE) actually produces a result on its own.

Any idea how I can fix this?

```r
shinyServer(function(input, output, session) {
...
output$tb1 <-  DT::renderDataTable({
  text <-fileData()
  p = matrix(sapply(1:length(text), function(i) {text[i]}),length(text))
  DT::datatable(p, escape=FALSE,rownames = FALSE, colnames='Posts', options=list(scrollY=500))})
...
```

ui.R

```r
...
DT::dataTableOutput("tb1")
...
```

**Comment by yihui** [comment]
Could you provide a minimal reproducible example? I do not see such a problem:

```r
library(DT)
m = matrix('<iframe src="http://rstudio.com" width=400 />', 2, 2)
datatable(m, escape = FALSE)
datatable(m)
```

Note Facebook may not allow you to embed its pages as iframes in your page. Without a reproducible example, it is hard to guess what could be wrong there.

BTW, I'm not sure what you meant by `colnames='Posts'`. Do you only have one column in the data since the colnames you specified is of length one?
