### ISSUE TITLE
Global search behavior differs on server

### ISSUE THREAD

**Issue by carlganz** [rstudio/DT#453]
On client, global search treats each word in the search separately, while server side global search only searches the entire string.

MRE:

```{R}
library(shiny)
library(DT)
mtcars2 = head(mtcars[, 1:5], 20)
mtcars2$model = rownames(mtcars2)
rownames(mtcars2) = NULL
options(DT.options = list(pageLength = 5))
# global search
ui <- fluidPage(
  DT::dataTableOutput("test"),
  DT::dataTableOutput("test2")
)

server <- function(input, output, session) {
  output$test <- DT::renderDataTable({
    datatable(mtcars2, options = list(searchHighlight = TRUE, search = list(search = 'da 16')))
  }, server = FALSE)
  output$test2 <- DT::renderDataTable({
    datatable(mtcars2, options = list(searchHighlight = TRUE, search = list(search = 'da 16')))
  }, server = TRUE)
}

shinyApp(ui,server)
```

I suggest replacing `q$search[['value']]` [here](https://github.com/rstudio/DT/blob/master/R/shiny.R#L394) with `gsub(' ', '|', q$search[['value']])`.

**Comment by shrektan** [comment]
I guess to implement the 100% same querying logic in both R and datatable's javascript side will be difficult. However, for this specific question, I may be able to help...

@yihui What do you think?

**Comment by carlganz** [comment]
Yeah I realize my suggestion won't work, and this is probably difficult to implement.

**Comment by yihui** [comment]
Actually I like this idea. I think it is easy enough to provide an option for users who want spaces to mean "OR" in the keyword, e.g., `getOption('DT.search.space_OR', FALSE)` (i.e. default to `FALSE`; when enabled, do `gsub('\\s+', '|')`).

**Comment by yihui** [comment]
This turns out to be trickier than I imagined, but eventually I figured it out. Now smart filtering has been enabled for server-side processing: https://datatables.net/reference/option/search.smart I should have left this task to @shrektan since it was actually a quite interesting challenge, but after I spent a few hours on it, I just finished it.

You can certainly disable smart filtering; see the relevant NEWS item 116377810ec0acbbd8c693632ee5f03ac5a79371

As I said in the comments of the code, the implementation is probably not efficient, but I don't have more time to optimize it.
