### ISSUE TITLE
DT datatable callback function not working after update

### ISSUE THREAD

**Issue by hiltonmbr** [rstudio/DT#492]
Using this example:

```

tb <- DT::renderDT({
 DT::datatable(data,
callback = JS("table.on('click.dt', 'tr', function() {
                Shiny.onInputChange('rows', table.rows(this).data().toArray() );
    });"))

},server=TRUE)


observeEvent(input$tb_rows_selected, {
  print(input$rows)
})
```

Shiny returns input$rows NULL.

Any ideas?

**Comment by yihui** [comment]
1. Could you provide a full example (one that I can just copy and run)?
2. Have you tried the dev version? `devtools::install_github('rstudio/DT')`

Thanks!

**Comment by hiltonmbr** [comment]
It was solved. Thanks!

**Comment by ImSanjayChintha** [comment]
can I know how it was resolved? I am facing same issue.

**Comment by bcastane** [comment]
Hi! 
I had the same issue. After doing some research i found out that the callback was working fine, but the table change its id so the css selector that i was using stopped pointing to the right table.

In summary every time that you "refresh" with a reactive object it increase the number on the id: DataTables_Table_0_wrapper... 

In order to solve it use the id in the top that dosent change (id: table_div_cat)

**Comment by shrektan** [comment]
As usual, if you think it's really something related to DT the package itself, please open a new issue ticker with a reproducible example. Otherwise, we can't help with this.

Thanks.

**Comment by bcastane** [comment]
Its not an issue on the DT itself, it is how it works and its already solved in my comment (i added the answer here for the people that thought that was an error on the package, but it only was an css selector problem)
