### ISSUE TITLE
StyleInterval not working for dates

### ISSUE THREAD

**Issue by jnolis** [rstudio/DT#495]
Similar to this [Stack Overflow issue](https://stackoverflow.com/questions/47764806/colour-background-with-styleinterval-of-shiny-date-datatable), I am having trouble setting the style of cells based on dates. It seems like this should work just as well as it does with numbers, but for some reason all dates get the same coloring.

```r
library(shiny)
library(DT)
library(tidyverse)
library(lubridate)

ui <- fluidPage(
  titlePanel("DateDemo"),
  sidebarLayout(
    sidebarPanel(
    ),
    mainPanel(
      DTOutput('tbl'),
      width = 10,
      height = "800px")
  )
)

server <- function(input, output) {
  output$tbl <-
    renderDT({
      data_frame(ExampleDate = as.Date(c("2018-01-01","2019-01-01"))) %>%
        datatable() %>%
        formatStyle(columns = "ExampleDate",
                    backgroundColor = styleInterval(as.Date("2018-02-02"), c("#FB717E","#89EC6A")))
    })
}
shinyApp(ui = ui, server = server)
```

![image](https://user-images.githubusercontent.com/3317138/35874949-bac404ce-0b22-11e8-8c97-94550065ce2c.png)

**Comment by shrektan** [comment]
Thanks for the report and I can confirm the bug. I think it's because [`formatInterval()`](https://github.com/rstudio/DT/blob/master/R/format.R#L261-L273) doesn't handle `Date` as a special class and generate incorrect JS callback for the `Date` column.  I will try to file a PR tomorrow.

### Some notes for myself...

The easiest solution is to change https://github.com/rstudio/DT/blob/master/R/format.R#L270 to something like the following codes. However, it may not work when the Date column is not formatted in `%Y-%m-%d`. Will investigate tomorrow...

```r
 if (is.Date(cuts)) {
      cut_ <- paste0("'", cuts[i], "'")
    } else {
      cut_ <- cuts[i]
    }
    js = paste0(js, sprintf('value <= %s ? %s : ', cut_, values[i]))
```
