### ISSUE TITLE
Error in tolower(x): invalid multibyte string 290 error

### ISSUE THREAD

**Issue by gnawhnehpets** [rstudio/DT#497]
Hello,

I have a shiny app that uses DT, and it runs perfectly locally. However, when I try entering a search term into the app while it is hosted on AWS EC2, I get the following error:

> DataTables warning: table id= DataTables_Table_0 - Error in tolower(x): invalid multibyte string 290

Here is the app location: http://ec2-34-227-113-253.compute-1.amazonaws.com:3838/myapp/

I hope you can help troubleshoot the issue.

Currently running R 3.4.3 on the EC2 instance.

**Comment by yihui** [comment]
Without seeing your `sessionInfo()`, here is only a blind guess:

Try to set the environment variable `LANG` to a value that is not `C` before you start R, e.g., `LANG=en_US.UTF-8`, so that multibyte characters can be supported well.

**Comment by ksbystrom** [comment]
I have the same problem

**Comment by yihui** [comment]
And I repeat myself.

**Comment by onlyphantom** [comment]
Not sure if the problem was solved already, but I went into debugging mode on this, and the problem seems to not lie in the `DT` library itself but with the encoding of the file. In my case, what helped was opening the file and `write.csv(thedf, "data_input.csv", encoding="UTF-8")`. When I use a file that is properly encoded the search works perfectly fine.

**Comment by AlexGriffiths** [comment]
The above was a huge help to me but I had to make one change, it seems the "encoding" argument should be specified as "fileEncoding" as per the below:

`write.csv(thedf, "data_input.csv",  fileEncoding = "UTF-8")`

**Comment by fjlmarco** [comment]
write.csv(thedf, "data_input.csv", fileEncoding = "UTF-8") worked for me as well.

**Comment by sgrubsmyon** [comment]
Just in case your data source is a MySQL database using `RMySQL`: Running

```
dbSendQuery(conn, "SET NAMES utf8")
```

in the header of my `server.R` fixed the problem for me very neatly. See also https://stackoverflow.com/questions/12869778/fetching-utf-8-text-from-mysql-in-r-returns.

**Comment by shrektan** [comment]
I take a bold guess that most of the cause is a corrupted file or not-correct-encoded characters.

The advice is: _always write UTF-8 encoded character to local files,  if there's any chance that the data contains non-ASCII strings._ Or more simply, always uses `readr::read_csv()` and `readr::write_csv()` to read and write csv files.
