### ISSUE TITLE
callback function not working on >=0.4  version

### ISSUE THREAD

**Issue by jyjek** [rstudio/DT#535]
Hi, 
I'm using code below. It's work fine on 0.2 version, but didn't work >=0.4 version

```
library(shiny)
library(DT)
shinyApp(
  ui = fluidPage(
    DT::dataTableOutput('foo'),
    verbatimTextOutput('selected_rows')
  ),
  server = function(server, input, output) {
    output$foo <- DT::renderDataTable({
      DT::datatable(iris,
                rownames = F,
                options=list(columnDefs = list(list(className = 'no_select', targets = 2) )),
                callback = JS("    /* disable row selecting for some columns */
                                     table.on('click', 'td.no_select', function() {
                                     var td = $(this), row = table.row(td.closest('tr'));
                                     if ($(td.node()).hasClass('selected')) {
                                     $(td.node()).removeClass('selected');
                                     }
                                     });"))
    })
    output$selected_rows <- renderText({
      input$foo_rows_selected
    })
  })
```

Thanks

**Comment by shrektan** [comment]
The example code seems wrong to me. Although it seems working in DT v0.2, I suspect it's due to luck. Open the developer tool and you can see that the callback function reports errors. It's the errors that stop the selection even from being calling. After changing `$(td.node())` to `$(row.node())`(actually in the row selection mode, the `td` won't have the class `selected`), the code won't work on my computer, even in version 0.2.

**Comment by jyjek** [comment]
Can you help me make the same true functionality with latest versions please?

**Comment by jyjek** [comment]
it's something like that 
` callback = JS("table.on('click', 'td.no_select', function() {return false});")`

**Comment by shrektan** [comment]
Well, in fact, I don't understand your exact intent. If you don't want the row to be selected when clicking certain cells (which seems quite strange to me because that row can still be selected by clicking other cells in the same row), I think it's difficult and I don't have a solution. 

Anyway,  you can ask questions on [stackoverflow](http://stackoverflow.com/) with tags `DT` and `R`.

Thanks.

**Comment by shrektan** [comment]
Close since no follow-up.
