### ISSUE TITLE
Feature request: add support for class "hms"

### ISSUE THREAD

**Issue by prosoitos** [rstudio/DT#537]
This would be great when working with `readr::parse_time()`.

These issues might be relevant: jeroen/jsonlite#62 and jrowen/rhandsontable#242.

Example:

``` r
library(tidyverse)
library(DT)

df <- tibble(
  a = 1:2,
  time = parse_time(c("9:23", "14:05"), "%H:%M")
)

df
#> # A tibble: 2 x 2
#>       a time  
#>   <int> <time>
#> 1     1 09:23 
#> 2     2 14:05
```

![image](https://user-images.githubusercontent.com/4634851/39450874-a1713a6e-4c81-11e8-892d-b22258b1fae3.png)

**Comment by shrektan** [comment]
I'm afraid I'm not sure what to do to help you on this case since DT relies on htmlwidgets (which relies on jsonlite) to serialize the R objects to JSON. If jsonlite doesn't support the `hms` class, neither can DT. The workaround is to convert the `hms` class object to `character` before passing to DT.

Welcome to correct if I misstated anything, thanks.

**Comment by prosoitos** [comment]
That is also how I understand the situation and I read jeroen/jsonlite#62. But I thought that I would ask, in case someone at RStudio had a solution.

**Comment by yihui** [comment]
I don't have a solution, other than the `as.character()` approach @shrektan mentioned. Thanks!
