### ISSUE TITLE
Scientific notation sorting

### ISSUE THREAD

**Issue by hou** [rstudio/DT#612]

**Comment by hou** [comment]
This actually a feature request. It would be great if the author could implement the Scientific notation sorting plugin: https://datatables.net/plug-ins/sorting/scientific

**Comment by philibe** [comment]
It works yet.

A priori, I think, every almost features in datatables.net are in DT but not documented.

```R
library(shiny)
library(scales)

server <- function(input, output) {

    df_react<-  reactive({
    
    numb<-c(0.05, 0.05671, 0.000000027)
    formatC(numb, format = "e", digits = 2)
    df <- as.data.frame(matrix(
                      c(formatC(numb, format = "e", digits = 2),
                      numb), 
             nrow = 3, ncol = 2))
    return(df)
  })
  
  output$toto<-DT::renderDataTable(DT::datatable( df_react(),
     options = list(
             columnDefs = list(
               list(type = scientific, targets = 0)
             ),
             order =list(
               list(1, 'desc')
             )
         )
  ))
  
}

ui <- shinyUI(fluidPage(
  DT::dataTableOutput('toto')
))

shinyApp(ui = ui, server = server)
```

**Comment by shrektan** [comment]
First of all, the sorting plugin only supports the client-side processing mode, according to https://datatables.net/plug-ins/sorting/ :

> Please note that these plug-ins are used for client-side processing only. Server-side processing performs sorting actions on the server-side.

Moreover, I think the browser or dataTable itself somehow already support the scientific sorting by default, you can try the following example. 

N.B: 

- It's not documented but I've tested it on Safari and Chrome, both work. 
- Only true if you are on the client-side mode. 
- Not true for the server-side mode, where the sorting is done by the server - R

The last, from https://rstudio.github.io/DT/plugins.html we know that only two sorting-natural and Filtering-searchHighlight plugins are included in DT (and should use the param `plugin` rather than `extension`). If you really need the plugin, please let me know.

# Example

Please sort any of the columns, you will find the row names are always ranked from 1 to 4 or 4 to 1.

```r
library(shiny)

tbl <- local({
  numb <- sort(c(2.95, 1.05671, 0.0000023,  0.000000027))
  data.frame(
    v1 = formatC(numb, format = "E", digits = 2),
    v2 = formatC(numb, format = "E", digits = 2),
    v3 = numb,
    stringsAsFactors = FALSE
  )
})

server <- function(input, output) {
  output$dt <- DT::renderDT(
    tbl, 
    server = FALSE
  )
}

ui <- basicPage(
  DT::DTOutput('dt')
)

shinyApp(ui = ui, server = server)
```

**Comment by shrektan** [comment]
Close as no response from the author.

In addition, I have double-checked that at least on Chrome and Safari, in the client-side processing mode, the table will recognize scientific notation automatically and no need to use the scientific sorting plugin.

**Comment by gorgitko** [comment]
Hello, just for everyone encountering this problem:

The current solution is to use

```
columnDefs = list(
  list(type = "num-fmt", targets = 0)
)
```

According to [columns.type](https://datatables.net/reference/option/columns.type) documentation, `num-fmt` stands for

> Numeric sorting of formatted numbers. Numbers which are formatted with thousands separators, currency symbols or a percentage indicator will be sorted numerically automatically by DataTables.

but it also applies to the scientific notation.
