### ISSUE TITLE
R datatable server-side search option doesn't handle exotic encoding (latin1)

### ISSUE THREAD

**Issue by phileas-condemine** [rstudio/DT#656]
# Context 
I've been trying to develop an R Shiny webapp using DT to display a datatable. I need to use an input to fill the datatable search option as I'm filtering and ordering the possibles search-terms by term-freq. My data is in french, therefore it includes accents with latin1 encoding (I tried UTF8 encoding but the rendering gets messy).

# My attempts
I compared renderDataTable behaviours in server-side computing and client-side computing. The client-side works well, but the data is to large to be handled that way. The server-side finds no match for accentuated terms (french accents).

Here is a repex

```
library(shiny)
library(DT)
data=data.frame(index=1:6,nom=c("hého","bonjour","enchanté","merci","où ça ?","à qui s'adresse-t-il ?"),stringsAsFactors = F)

ui <- fluidPage(
  title = 'Use the DT package in shiny',
  selectizeInput(inputId = 'tag',label="mots pour filtrer",
                 choices=strsplit(data$nom,split = " ")%>%unlist%>%unique),  
  h3('A Table Using Client-side Processing'),
  fluidRow(
    DT::dataTableOutput('tbl_a')
  ),
  h3('A Table Using Server-side Processing'),
  fluidRow(
    DT::dataTableOutput('tbl_b')
  )
)
server <- function(input, output, session) {
  output$tbl_a = DT::renderDataTable(datatable(data,options=list(search=list(search=input$tag))), server = FALSE)
  output$tbl_b = DT::renderDataTable(datatable(data,options=list(search=list(search=input$tag))))
}


shinyApp(ui,server)
```

Client-side Processing returns the desired result... But I'd like to achieve that with server-side processing.

# Session info
Here is the output of a call to `xfun::session_info('DT')`

```
R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134), RStudio 1.2.1330

Locale:
  LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252   
  LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
  LC_TIME=French_France.1252    

Package version:
  assertthat_0.2.1   BH_1.69.0.1        cli_1.1.0         
  colorspace_1.4.1   crayon_1.3.4       crosstalk_1.0.0   
  digest_0.6.18      DT_0.5.3           fansi_0.4.0       
  ggplot2_3.1.1      glue_1.3.1         graphics_3.5.3    
  grDevices_3.5.3    grid_3.5.3         gtable_0.3.0      
  htmltools_0.3.6    htmlwidgets_1.3    httpuv_1.5.1      
  jsonlite_1.6       labeling_0.3       later_0.8.0       
  lattice_0.20.38    lazyeval_0.2.2     magrittr_1.5      
  MASS_7.3.51.1      Matrix_1.2.15      methods_3.5.3     
  mgcv_1.8.27        mime_0.6           munsell_0.5.0     
  nlme_3.1.137       pillar_1.3.1       pkgconfig_2.0.2   
  plyr_1.8.4         promises_1.0.1     R6_2.4.0          
  RColorBrewer_1.1.2 Rcpp_1.0.1         reshape2_1.4.3    
  rlang_0.3.4        scales_1.0.0       shiny_1.3.0       
  sourcetools_0.1.7  splines_3.5.3      stats_3.5.3       
  stringi_1.4.3      stringr_1.4.0      tibble_2.1.1      
  tools_3.5.3        utf8_1.1.4         utils_3.5.3       
  viridisLite_0.3.0  withr_2.1.2        xtable_1.8.3      
  yaml_2.2.0
```

https://stackoverflow.com/questions/55574984/r-datatable-search-option-doesnt-handle-exotic-encoding-latin1

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.name/issue/.
- [x] I have provided the necessary information about my issue.
    -  If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - [x] If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('DT')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/DT')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

**Comment by shrektan** [comment]
Thanks for reporting the issue. Especially a big thank you for respecting the issue template.

I can reproduce this, although it's a bit of surprising that I haven't noticed this earlier, considering I'm using Chinese every day on Windows... Maybe because I usually deploy the apps on Docker...  

Will fix as soon as we can.

**Comment by shrektan** [comment]
The cause of this bug is that after https://github.com/rstudio/httpuv/commit/9ed9a1f557735b49be1082719261d199b8d83d68 , `shiny::parseQueryString()` now assumes the input is always UTF-8 encoding (See the screenshots below but I'm not sure if it's expected or a bug). 

<img width="461" alt="image" src="https://user-images.githubusercontent.com/8368933/56082647-d032e580-5e4d-11e9-9339-3aeb9a31e602.png">

However, in DT, due to some reasons, the query strings are converted to the native encoding before calling `shiny::parseQueryString()`. It results in native encoded strings being marked as UTF-8, wrongly.

https://github.com/rstudio/DT/blob/f60a2e755e7bc1495d082ef7a8949c765898593f/R/shiny.R#L477-L484

So the solution for this bug could be one of the following:

- Simply use UTF-8 strings because [the patch mentioned in the comment](https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16264) has been merged.
- Converted the parsed list to the native encoding after `shiny::parseQueryString()` being called.

What do you think, @yihui ?

The version of shiny and httpuv on my computer:

```
> packageVersion('httpuv')
[1] ‘1.5.1’
> packageVersion('shiny')
[1] ‘1.3.1’
```

**Comment by phileas-condemine** [comment]
I used iconv(to="UTF-8") on input$tag and it fixes it, a bit tricky though.
https://stackoverflow.com/questions/55574984/r-datatable-search-option-doesnt-handle-exotic-encoding-latin1/55811357#55811357

```
xfun::session_info('DT')
library(shiny)
library(DT)
data=data.frame(index=1:6,nom=c("hého","bonjour","enchanté","merci","où ça ?","à qui s'adresse-t-il ?"),stringsAsFactors = F)

ui <- fluidPage(
  title = 'Use the DT package in shiny',
  selectizeInput(inputId = 'tag',label="mots pour filtrer",
                 choices=strsplit(data$nom,split = " ")%>%unlist%>%unique),  
  h3('A Table Using Client-side Processing'),
  fluidRow(
    DT::dataTableOutput('tbl_a')
  ),
  h3('A Table Using Server-side Processing'),
  fluidRow(
    DT::dataTableOutput('tbl_b')
  ),
  h3('A Table Using Server-side Processing'),
  fluidRow(
    DT::dataTableOutput('tbl_c')
  )
)
server <- function(input, output, session) {
  output$tbl_a = DT::renderDataTable(datatable(data,options=list(search=list(search=input$tag))), server = FALSE)
  output$tbl_b = DT::renderDataTable(datatable(data,options=list(search=list(search=enc2native(input$tag),regex=T))))
  output$tbl_c = DT::renderDataTable(datatable(data,options=list(search=list(search=iconv(input$tag,to = "UTF-8"),regex=T))))
}


shinyApp(ui,server)
```

**Comment by yihui** [comment]
@shrektan Let's try the first approach you mentioned (i.e. get rid of `iconv()`). Feel free to push to the master branch. No need to send a pull request. Thanks!

I wonder if @phileas-condemine solution would still work with our fix, though.

**Comment by shrektan** [comment]
Honestly speaking, it's a suprise for me that @phileas-condemine 's solution works... What `iconv(input$tag,to = "UTF-8")` returns are garbage letters because `input$tag` is always `UTF-8` encoded already, isn't it? 

Anyway, @phileas-condemine, I checked the solution won't work after the fix, please pay attention to that... Thanks.
