### ISSUE TITLE
The dataIndex argument of rowCallback does not work.

### ISSUE THREAD

**Issue by stla** [rstudio/DT#699]
Hello,

 Normally the `rowCallback` function has five arguments. The last one [does not work](https://stackoverflow.com/q/57521490/1100107) with `DT`.

**Comment by shrektan** [comment]
Please respect the issue template. At least please provide a minimal example. Thanks.

**Comment by stla** [comment]
@shrektan Ok, sorry.

```
library(DT)

rowCallback <- c(
  "function(row, data, displayNum, displayIndex, dataIndex){",
  "  console.log(dataIndex);",
  "}")

datatable(iris, options = list(rowCallback = JS(rowCallback)))
``` 

The console prints `undefined`.

**Comment by shrektan** [comment]
@ Thanks for reporting. I believe it's because of the version of datatables library. The latest version is 1.10.19 but DT currently uses 1.10.16, which doesn't support the fifth argument in rowCallback function.

I've created an example on [jsfiddle](https://jsfiddle.net/ojmg3u0s/). Note if you change the resource from `https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js` to `https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js.`, the fifth argument can be displayed.

**Comment by stla** [comment]
Ok thanks @shrektan . It's time to update then. We already discussed that with yihui. I will try to help if I find some time.
