### ISSUE TITLE
Why not add a option like 'Single/Multiple/None' for the row selection?

### ISSUE THREAD

**Issue by shrektan** [rstudio/DT#78]
Hi, Yihui, I noticed that you've added the row selection feature for DT. Very nice.

However, I can't find **an option to choose the row selection mode**. You know, sometimes I don't want to have the row selection feature, and sometimes I just want to select one row per time...

can we have something like the `tableTools`' option?

```r
options = list(
    tableTools = list("sRowSelect" = "single",
                             aButtons = "")
)
```

Thanks.

**Comment by yihui** [comment]
That sounds like a good idea. I'll think about it. Thanks!

**Comment by yihui** [comment]
Done.

**Comment by shrektan** [comment]
Great! Thanks! Love it!

**Comment by jasdumas** [comment]
I like the feature of just selecting a single row, but I would like to access the current row selected so that I can print out just the single selection. ie: `input$foo_rows_selected` prints out all of the rows that were selected. `input$foo_row_current_selected` would be useful for populating select boxes

**Comment by yihui** [comment]
@jasdumas Please use `input$foo_row_last_clicked` with the latest version of DT: http://rstudio.github.io/DT/shiny.html
