### ISSUE TITLE
Buttons slow to load

### ISSUE THREAD

**Issue by deepanshu88** [rstudio/DT#814]
Thanks for a great package. When I am using Buttons extension with extend = 'collection' and adding custom button, it takes higher time in loading the app than usual. I also tried server = FALSE it didn't help much. Is it a usual in DT JS library? I tried all the possible combinations to figure out what exactly causing the issue (removing some formating functions and later found it's do with Buttons only)
```r
library(DT)
TableName <- 'Deal View'
eps <- 1E-5
report <-  paste0("function (e, dt, node, config) {reportIssue(e, dt, node, config, tableName =", "'", TableName, "'",  ");}")


datatable(
  iris, rownames=FALSE,
  extensions = 'Buttons',
  options = list(
    paging = FALSE, searching = FALSE, ordering=F, info = FALSE,
    dom = 'Bfrtip',
    buttons = list(
      list(
        extend = 'collection',
        text = '<i class="fa fa-bars"></i>',
        buttons = list(
          'copy', 'excel',
          list(extend = 'csv', text = 'Report Issue', action = JS(report))
        ), 
        text = 'Export'
      )
    )
  )
) 
```

**Comment by shrektan** [comment]
It should be fast and not slow, in my opinion. But we need a reproducible example in order to trace the cause.

**Comment by shrektan** [comment]
Sorry, I see that your example is reproducible just need a small change. I've edited your original example code.

However, it runs very fast on my computer. Do you use IE? Have you tried Chrome or Safari?

**Comment by deepanshu88** [comment]
I use Chrome only. It runs fast in my local machine. But when I deploy app via container (shinyproxy) it is slower when I open the app in different machines. Container starts fine (with no big delay), then UI loads perfectly fine and then it takes time for DT to process things. I tested everything else. If I remove this button function, it loads very fast. Is it something to do with server side processing SERVER = TRUE?

**Comment by shrektan** [comment]
No, it should have nothing to do with `server = TRUE`, in my opinion, as you said, only the button function causes the trouble but `server = TRUE` only affects the data. Anyway, you can easily test this by setting `server = FALSE`. 

Since you have mentioned that you are using shinyproxy as the container, AFAIK, they have a bug on Ajax Posting in previous versions. So my suggest is that, you can try to run your app in a plaint docker container. If it's ok, then it's a problem of shinyproxy.

BTW, you should check that the DT/shiny/htmltools version in your docker image is the latest, as it may differ from the version you used in your local machine.
