### ISSUE TITLE
Value of `input$foo_cells_selected` when no cell is selected is `<0 x 0 matrix>` instead of `NULL`

### ISSUE THREAD

**Issue by Mosk915** [rstudio/DT#819]
When row or column selection is enabled, the value of  `input$foo_rows_selected` or  `input$foo_columns_selected` when no row or column is selected is `NULL`.  When cell selection is enabled, the value of  `input$foo_cells_selected` when no cell is selected is `<0 x 0 matrix>`.

This causes a minor annoyance when I observe the cell selection since I only want to trigger the `observeEvent` when a cell is selected but not when it is deselected.  With row and column selection this isn't an issue since `observeEvent` ignores nulls by default.  But with cell selection, a workaround is needed to check if the length of `input$foo_cells_selected` is greater than 0.

Is it possible to have `input$foo_cells_selected` be `NULL` when no cell is selected, or would changing that create more problems than it resolves?

---

By filing an issue to this repo, I promise that

- [ ] I have fully read the issue guide at https://yihui.name/issue/.
- [ ] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('DT')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/DT')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [ ] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by shrektan** [comment]
I think you are right that we should make this more consistent.

**Comment by shrektan** [comment]
Sorry, after a second thought, we may not change this for the present. The reasons are:

1. We may break users' existing code as `nrow(NULL)` returns `NULL` not `0`;
1. We could easily check the current behavior by using `length()` because both `length(NULL)` and `length(matrix(double())` returns 0;
1. It may be difficult to implement, as the JS `changeInput()` function in shiny seems can't update a `NULL` value if the previous value is `shiny.matrix` (I haven't looked into the cause but it's what I've observed so far).

So, I'll close this for now, and please feel free to reopen if you have more arguments.

Thanks.

**Comment by Mosk915** [comment]
Thanks, I understand.  I suspected it may have been more difficult than it seemed.  Checking the length works fine so I’ll continue to do that.
