### ISSUE TITLE
button not working when download via browser

### ISSUE THREAD

**Issue by liutiming** [rstudio/DT#912]
This is technically not a bug report because the default workflow is to use the rendered html directly, but I realise that when the html is downloaded from a browser (tried Firefox and Chrome), the button will not work in the downloaded html. Just FYI.

**Comment by shrektan** [comment]
I don’t think I understand your issue. You mean when you saved the webpage to a local file and reopened it, the button extension didn’t work?

**Comment by liutiming** [comment]
that's what happened to me

**Comment by yihui** [comment]
I don't expect that to work. By saving an HTML page using the web browser, the JavaScript code in it doesn't necessarily work. This is quite complicated. The only reliable way to make it work is to download the original `.html` file (which means the page author has to provide a separate download link).

This issue is not specific to DT, but pretty much any JavaScript applications. It's unlikely that we'll fix it. Sorry.

**Comment by liutiming** [comment]
No problem. Thanks!
