### ISSUE TITLE
`updateFilters()` enhancements

### ISSUE THREAD

**Issue by mikmart** [rstudio/DT#971]
It was great to see the new `updateFilters()` function added recently – thanks @wholmes105!

After some testing, there’s a couple of useful enhancements I had in mind:

1.  Currently `updateFilters()` errors out if the data contains integer or character columns. I don’t think there’s any reason for this behaviour? Integer filters should update like other numerics, and character can just be skipped.
2.  It would be nice to have the updated limits match those that would be calculated if the table were re-rendered with the new data. I believe this would require refactoring the internal `filterRow()` function so as to be able to re-use the limit calculations there.
    -   For example factors should use `levels()`, not `unique()` for limits.
3.  Limits for numeric columns currently ignore the internal `scale` applied to the slider widgets. As a result, the updated limits are correct only when the column happens to have a maximum of 1 decimal places in the data (or 0 for dates, 3 for datetimes).
4.  Filters that were `disabled` on the initial render don’t have their limits updated or enabled. That’s because the HTML for them is never created. Fixing this might require a more thorough refactoring for `filterRow()`.

Here’s a reprex app demonstrating some of the issues I mentioned:

``` r
library(shiny)
library(DT)

tbl <- data.frame(
  num1 = seq(-2, 2) / 1,
  num2 = seq(-2, 2) / 10,
  num3 = seq(-2, 2) / 100,
  num4 = replace(seq(-2, 2) / 100, 1, Inf),
  dttm = round(Sys.time()) + seq(-2, 2) * 3600,
  fct1 = factor(c("A", rep("B", 4)), levels = c("A", "B", "C")),
  fct2 = factor(c(rep("A", 4), "B"), levels = c("A", "B", "C"))
)

ui <- fluidPage(
  sliderInput(
    "rows",
    "Slice rows",
    min = 0,
    max = nrow(tbl),
    value = c(1, 4),
    step = 1
  ),
  DTOutput("table"),
)

server <- function(input, output, session) {
  output$table <- renderDT(datatable(tbl, filter = "top"))
  
  tbl_slice <- eventReactive(input$rows, {
    r1 <- input$rows[1]
    r2 <- input$rows[2]
    tbl[seq(r1, r2), ]
  })
  
  proxy <- dataTableProxy("table")
  observeEvent(tbl_slice(), {
    replaceData(proxy, tbl_slice())
    updateFilters(proxy, tbl_slice())
  })
}

shinyApp(ui, server)
```

I’ve been exploring some solutions, and would be happy to discuss further, if there’s interest in this.

**Comment by wholmes105** [comment]
Hi @mikmart,

I'm happy to discuss potential improvements with you or anyone else looking to contribute. In response to your recommendations and reprex above:

1. You are correct that integers should be treated the same as numerics; turns out that `inherits(integer(1), 'numeric')` comes back as `FALSE`, unlike a call to `is.numeric()`. Correcting this should (hopefully) be as simple as changing `inherits(x, c("numeric"))` to `inherits(x, c("numeric", "integer"))`. For characters, we might be able to treat them with the same logic as factors and logicals, but that would depend on the JavaScript logic DT's filters already use. `updateFilters` converts the latter two classes into characters before sending them to the JavaScript side, though, so it should work.
2. Does this refer to what happens when you set the lower bound in the slider to be 0 in the reprex, or when the slider is set to `2:4`, where both `fct1` and `fct2` have one option visible in the data but two options visible in the filter? In the case of the latter,  your example has as level "C" that is never used in `tbl`.
   - It is worth noting that when I use the logic from `updateFilters()` to check what the filters should be for tbl[2:4,] (see below), `fct1` and `fct2` only have 1 level each, which is not the behavior demonstrated in your app. I am currently unsure why this behavior would change in the app versus in my R console.
   - `lapply(tbl[2:4,], function(x) {...})`
3. To be clear, you are referring to the slider widgets produced by `nouislider` and used by `DT` to produce the filters within each column and _not_ the sliders produced by `Shiny`, right? I don't see any use of `scale` in your reprex, and the nouislider [options page](https://refreshless.com/nouislider/slider-options/) doesn't seem to mention a `scale` argument, either. Could you elaborate where specifically the ignored option is in the example above?
4. You are correct that `updateFilters()` as written only updates existing html, so it carries an implicit assumption that all filters the user wants to update already exist
   - My first instinct for fixing that would be to, for and datatable where column filters are being used, fully create the html for all filters and then selectively disable the column filters that are not wanted. This would maintain the same default behavior for the end user, but allow for the filters to be prepared in advance in case they need to be updated later.
   - However, for this to work, there would also need to be a new pair of functions (say, `enableColFilters` and `disableColFilters`) to enable and disable the column filters in response to their updated contents. Alternatively, a single function `updateColFilters` could have two arguments, one for enabling specific column filters and one for disabling them. Honestly, this wouldn't be a bad thing to have in general, but that would probably qualify as a separate feature on its own.

**Comment by mikmart** [comment]
Thanks for taking the time to look into this! I do appreciate it. Here's some further thoughts:

### Column types

Character columns currently don't use a select input option, just a search. As a result, they don't really have a concept of limits, so `updateFilters()` should be a no-op for them.

And yeah, I agree with integers: allowing for them should be straightforward.

### Consistent behaviour

Factor levels are a part of it, but there's also some other subtle changes. Like on initial render by `filterRow()`, boolean columns always include both options, regardless of whether they are present in the data or not:

https://github.com/rstudio/DT/blob/815872d67141bb053ed9defd6b72cbaed2aa6668/R/datatables.R#L687-L689

And for numeric columns there's potentially some rounding happening for the range, too:

https://github.com/rstudio/DT/blob/815872d67141bb053ed9defd6b72cbaed2aa6668/R/datatables.R#L666-L667

For factors, the default behaviour is to have filter options include all levels regardless of whether they are used or not:

https://github.com/rstudio/DT/blob/815872d67141bb053ed9defd6b72cbaed2aa6668/R/datatables.R#L691-L692

This seems useful, and is also more general than just using `unique()` values that do appear -- particularly because you can just `droplevels()` before `updateFilters()` in order to revert back to the `unique()` behaviour.

Regarding `fct2` options not updating in the app: there's an error in the JavaScript console that points to why:

```
Uncaught TypeError: new_vals.map is not a function
```

I think that's caused by the fact that there's only one unique value, which when converted to JSON for transfer to JS becomes a scalar instead of an array, while JS expects `new_vals` to always be an array. This error then causes the update to fail.

https://github.com/rstudio/DT/blob/815872d67141bb053ed9defd6b72cbaed2aa6668/inst/htmlwidgets/datatables.js#L79

### Scale

Yeah I'm talking about the `noUiSlider`s. The `scale` parameter is initially calculated here:

https://github.com/rstudio/DT/blob/815872d67141bb053ed9defd6b72cbaed2aa6668/R/datatables.R#L664
https://github.com/rstudio/DT/blob/815872d67141bb053ed9defd6b72cbaed2aa6668/R/datatables.R#L635-L641

And gets passed to JS as a data attribute in the HTML:
https://github.com/rstudio/DT/blob/815872d67141bb053ed9defd6b72cbaed2aa6668/R/datatables.R#L673

It's then used on the JavaScript side for the internal representation of slider values:

https://github.com/rstudio/DT/blob/815872d67141bb053ed9defd6b72cbaed2aa6668/inst/htmlwidgets/datatables.js#L533-L536

I believe this is the cause of the "numerics need to be multiplied by 10" symptom addressed in `updateFilters()` here:

https://github.com/rstudio/DT/blob/815872d67141bb053ed9defd6b72cbaed2aa6668/R/shiny.R#L493-L495

You can see that in the example app the limits for `num1` are wrong after updating (data range -2:1 maps to -20:10). And also for `num3`, where -0.02:0.01 maps to -0.002:0.001 limits. And also because of rounding the datetime, the limits are just wildly off.

### Disabled filters

Yeah I completely agree that it would be better to create the HTML for all filters, regardless of whether they end up disabled or not. I think that would mean refactoring these types of sections in `filterRow()`:

https://github.com/rstudio/DT/blob/815872d67141bb053ed9defd6b72cbaed2aa6668/R/datatables.R#L671-L682

I also think it would be useful to also have a function for enabling/disabling filters. I'm not sure it would be strictly _required_ for these changes though, more of an additional feature. For now, `updateFilters()` could still also take care of maintaining that status based on values in the data, like `filterRow()` currently does for the initial render.

**Comment by mikmart** [comment]
Just to summarise the status after the merged PRs:

- Limit finding logic is still duplicated in `filterRow()` and `updateFilters()`. Most inconsistencies should be ironed out, but potentially at least some rounding differences remain.
- Enabled/disabled status does not yet change on `updateFilters()`.

I think both could be addressed with a refactoring of `filterRow()`. I plan to have a look at that in the near future.

**Comment by mikmart** [comment]
With yesterday's changes, I belive everything raised here has been addressed. 🎉

I had one last look through the code, and found one bug of mine, and some little fixups I'd still like to make. I'll submit a PR for them shortly, closing this at the same time.

Thanks so much @wholmes105 for the discussion and @yihui for the speedy review and positive interactions. It's been a pleasure.
