### ISSUE TITLE
Bug: "'C:\Program' is not recognized as an internal or external command" while installing from CRAN on Windows

### ISSUE THREAD

**Issue by twolodzko** [rstudio/DT#98]
While installing DT on Windows from CRAN I get the following error message:

```
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
Warning in install.packages :
  running command '"C:/Program Files/R/R-3.2.0/bin/x64/R" CMD INSTALL -l "C:\Users\XXXX\Documents\R\win-library\3.2" C:\Users\XXXX\AppData\Local\Temp\XXXX/downloaded_packages/DT_0.1.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘DT’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\XXXX\AppData\Local\Temp\XXXX\downloaded_packages’
```

Because of that it is not possible to install DT. At the same time shiny has made `renderDataTable` depreciated and wants it imported from DT, so it makes this feature also not available from shiny.

It seems that there is some kind of brackets or slashes in path issue in the installation code.

**Comment by wch** [comment]
This seems like an issue with devtools. Are you using the latest version of devtools?

**Comment by yihui** [comment]
I have seen this devtools issue reported many times, although I have never been able to reproduce it. Anyway, DT is on CRAN now, so please just `install.packages('DT')`. If you really need to install the development version of DT, here is a workaround:

```r
install.packages(
  "DT",
  type = "source",
  repos = c("http://yihui.name/xran", "http://cran.rstudio.com")
)
```

**Comment by twolodzko** [comment]
Yes, the problem occurred after installing R + RStudio + libraries from the scratch on the brand new Windows PC.

**Comment by twolodzko** [comment]
@yihui I tried to install in from CRAN - the problem occurred when installing it from CRAN, but it also appears if installing using devtools from github.

**Comment by yihui** [comment]
I'm sorry, but what is the problem of `install.packages('DT')`?

**Comment by twolodzko** [comment]
@yihui the error message is an exact copy (with XXXX parts removed) of message that appears when installing from CRAN on fresh R + RStudio install.

**Comment by yihui** [comment]
Okay, that might be a bug of R (being unable to install source packages). If you are familiar with command line tools, you can just download the source package and install it manually via `R CMD INSTALL`; otherwise please just wait for one more day for the Windows binary package to be built on CRAN.

**Comment by ShaneZhong** [comment]
I just had the same problem yesterday, spent half of my day and I got this solved:

1) Uninstall R (not R-studio)
2) Install R under a directory that does not contain a space character, e.g. C:/R/R-3.3.1
3) Open R-studio
4) Under Tools -> Global Option -> General -> R version, select the new R directory
5) Install the packge you needed

The error is caused by the space character between 'Program' and 'Files'.

**Comment by yihui** [comment]
@ShaneZhong I'm not sure if you have seen my very first reply. Spending half of a day may not really worth it...

**Comment by shv38339** [comment]
@ShaneZhong  - had the same problem with installing `forcats` and your solution worked.

**Comment by Syed-Areeb-Zaidi** [comment]
@ShaneZhong thanks a lot buddy it worked but after that two more things 

install.packages("bitops")
library(bitops)

than install whatever you want to
